// Matthew O'Rourke Bourke
// 13/04/2026
// Project Snowflake

// PHASE 1

//create warhouse
CREATE OR REPLACE WAREHOUSE RESTAURANT_PROJECT_WH
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RESTAURANT_PROJECT_WH;

//create restaurant database
CREATE OR REPLACE DATABASE RESTAURANT_DB;

//use databse and public schema
USE DATABASE RESTAURANT_DB;
USE SCHEMA PUBLIC;

//create file format
CREATE OR REPLACE FILE FORMAT RESTAURANT_JSON
TYPE = JSON;

//create stage
CREATE OR REPLACE STAGE RESTAURANT_STAGE
URL = 's3://advdbsys/'
FILE_FORMAT = RESTAURANT_JSON;

LIST @RESTAURANT_STAGE;

//CREAte table
CREATE OR REPLACE TABLE restaurant_data (
    RAW_DATA VARIANT
);

//copy restaurants.json into the data table
COPY INTO restaurant_data
FROM @RESTAURANT_STAGE/restaurants.json
FILE_FORMAT = (FORMAT_NAME = RESTAURANT_JSON)
ON_ERROR = CONTINUE;

//list 10 from data table
select * from restaurant_data limit 10;

// PHASE 2

//creating table 2 and insert data
CREATE OR REPLACE TABLE RESTAURANT AS
SELECT
    RIGHT(RAW_DATA:_id['$oid']::STRING, 6) AS RESTAURANT_ID,
    RAW_DATA:name::STRING AS NAME,
    RAW_DATA:stars::NUMBER AS STARS,
    RAW_DATA:contact AS CONTACT,
    RAW_DATA:contact.phone::STRING AS PHONE,
    RAW_DATA:contact.email::STRING AS EMAIL,
    RAW_DATA:contact.location as LOCATION
FROM RESTAURANT_DATA
WHERE RAW_DATA IS NOT NULL;

select * from RESTAURANT limit 10;

//DROP TABLE RESTAURANT;

//create and insert data into table 3 - ******************THERE IS NO INSPECTION DATE IN THE DATA WE ARE PROVIDED*********************
CREATE OR REPLACE TABLE GRADE_TABLE AS
SELECT
    RIGHT(RAW_DATA:_id['$oid']::STRING, 6) AS RESTAURANT_ID,
    g.VALUE::NUMBER AS GRADE
FROM RESTAURANT_DATA r,
LATERAL FLATTEN(INPUT => r.RAW_DATA:grades) g
WHERE RAW_DATA IS NOT NULL;

SELECT * FROM GRADE_TABLE LIMIT 10;

//create and insert data into table 4
CREATE OR REPLACE TABLE CATEGORY AS
SELECT
RIGHT(RAW_DATA:_id['$oid']::STRING, 6) AS RESTAURANT_ID,
    C.VALUE::STRING AS CATEGORY_NAME
FROM RESTAURANT_DATA r,
LATERAL FLATTEN(INPUT => r.RAW_DATA:categories) C
WHERE RAW_DATA IS NOT NULL;

SELECT * FROM CATEGORY LIMIT 10;

// PHASE 4

// I
SELECT
    R.NAME,
    COUNT(C.CATEGORY_NAME) AS NUMBER_OF_CATEGORIES
FROM RESTAURANT R
JOIN CATEGORY C
    ON R.RESTAURANT_ID = C.RESTAURANT_ID
GROUP BY R.NAME
ORDER BY NUMBER_OF_CATEGORIES DESC, R.NAME;

// II
SELECT
    NAME, stars
FROM RESTAURANT
WHERE STARS = 5
ORDER BY NAME;

// III
SELECT DISTINCT
    R.NAME, C.CATEGORY_NAME
FROM RESTAURANT R
JOIN CATEGORY C
    ON R.RESTAURANT_ID = C.RESTAURANT_ID
WHERE UPPER(C.CATEGORY_NAME) = 'ITALIAN'
ORDER BY R.NAME;

// IV
SELECT 
    name, 
    location[0] AS "Longitude", 
    location[1] AS "Latitude"
FROM RESTAURANT;

// V
SELECT
    STARS,
    COUNT(*) AS NUM_OF_RESTAURANTS
FROM RESTAURANT
GROUP BY STARS
ORDER BY STARS DESC;

// VI
//1 - show restaurant and the avergae grade for it
SELECT
    R.NAME,
    ROUND(AVG(G.GRADE), 2) AS AVERAGE_GRADE
FROM RESTAURANT R
JOIN GRADE_TABLE G
    ON R.RESTAURANT_ID = G.RESTAURANT_ID
GROUP BY R.NAME
ORDER BY AVERAGE_GRADE DESC, R.NAME;

//2 - category and average star rating
SELECT
    C.CATEGORY_NAME,
    ROUND(AVG(R.STARS), 2) AS AVERAGE_STARS
FROM RESTAURANT R
JOIN CATEGORY C
    ON R.RESTAURANT_ID = C.RESTAURANT_ID
GROUP BY C.CATEGORY_NAME
ORDER BY AVERAGE_STARS DESC, C.CATEGORY_NAME;

//3 - restaurants with more than 3 categories
SELECT
    R.NAME,
    COUNT(C.CATEGORY_NAME) AS CATEGORY_COUNT
FROM RESTAURANT R
JOIN CATEGORY C
    ON R.RESTAURANT_ID = C.RESTAURANT_ID
GROUP BY R.NAME
HAVING COUNT(C.CATEGORY_NAME) > 3
ORDER BY CATEGORY_COUNT DESC, R.NAME;

//4 - restaurants with both their number of categories and number of grades
SELECT
    R.NAME,
    COUNT(DISTINCT C.CATEGORY_NAME) AS CATEGORY_COUNT,
    COUNT(DISTINCT G.GRADE) AS GRADE_COUNT
FROM RESTAURANT R
JOIN CATEGORY C
    ON R.RESTAURANT_ID = C.RESTAURANT_ID
JOIN GRADE_TABLE G
    ON R.RESTAURANT_ID = G.RESTAURANT_ID
GROUP BY R.NAME
ORDER BY CATEGORY_COUNT DESC, GRADE_COUNT DESC, R.NAME;

// VII - calculate average grade for each restaurant
WITH RESTAURANT_AVG_GRADE AS (
    SELECT
        RESTAURANT_ID,
        AVG(GRADE) AS AVG_GRADE
    FROM GRADE_TABLE
    GROUP BY RESTAURANT_ID
)

SELECT
    R.NAME,
    R.STARS,
    A.AVG_GRADE
FROM RESTAURANT R
JOIN RESTAURANT_AVG_GRADE A
    ON R.RESTAURANT_ID = A.RESTAURANT_ID
WHERE A.AVG_GRADE < 12
ORDER BY A.AVG_GRADE ASC, R.NAME;

// VIII - finds top 3 highest rated restaurant
SELECT
    C.CATEGORY_NAME,
    R.NAME,
    R.STARS,
    RANK() OVER (
        PARTITION BY C.CATEGORY_NAME
        ORDER BY R.STARS DESC, R.NAME
    ) AS CATEGORY_RANK
FROM RESTAURANT R
JOIN CATEGORY C
    ON R.RESTAURANT_ID = C.RESTAURANT_ID
QUALIFY CATEGORY_RANK <= 3
ORDER BY C.CATEGORY_NAME, CATEGORY_RANK, R.NAME;

// IX - stores the highest grade recorded for each restaurant, improves performance because the aggregation is precomputed
CREATE OR REPLACE MATERIALIZED VIEW MV_MAX_GRADE AS
SELECT
    RESTAURANT_ID,
    MAX(GRADE) AS HIGHEST_GRADE
FROM GRADE_TABLE
GROUP BY RESTAURANT_ID;

SELECT
    R.NAME,
    M.HIGHEST_GRADE
FROM RESTAURANT R
JOIN MV_MAX_GRADE M
    ON R.RESTAURANT_ID = M.RESTAURANT_ID
ORDER BY M.HIGHEST_GRADE DESC, R.NAME;

// PHASE 5

// create the share
CREATE OR REPLACE SHARE RESTAURANT_SHARE
SECURE_OBJECTS_ONLY = FALSE;

// share database and schema
GRANT USAGE ON DATABASE RESTAURANT_DB TO SHARE RESTAURANT_SHARE;
GRANT USAGE ON SCHEMA RESTAURANT_DB.PUBLIC TO SHARE RESTAURANT_SHARE;

// share tables
GRANT SELECT ON TABLE RESTAURANT_DB.PUBLIC.RESTAURANT TO SHARE RESTAURANT_SHARE;
GRANT SELECT ON TABLE RESTAURANT_DB.PUBLIC.GRADE_TABLE TO SHARE RESTAURANT_SHARE;
GRANT SELECT ON TABLE RESTAURANT_DB.PUBLIC.CATEGORY TO SHARE RESTAURANT_SHARE;

// share mv
GRANT SELECT ON MATERIALIZED VIEW RESTAURANT_DB.PUBLIC.MV_MAX_GRADE TO SHARE RESTAURANT_SHARE;

// add account
ALTER SHARE RESTAURANT_SHARE ADD ACCOUNTS = KHTPTQO.LW44087;

SHOW SHARES;
DESCRIBE SHARE RESTAURANT_SHARE;